export interface PackageSuggestion {
  name: string;
  ecosystem: string;
}

export const PACKAGE_SUGGESTIONS: PackageSuggestion[] = [
  // JavaScript / TypeScript — npm
  { name: "React", ecosystem: "npm" },
  { name: "Next.js", ecosystem: "npm" },
  { name: "Vue", ecosystem: "npm" },
  { name: "Nuxt", ecosystem: "npm" },
  { name: "Svelte", ecosystem: "npm" },
  { name: "SvelteKit", ecosystem: "npm" },
  { name: "Solid", ecosystem: "npm" },
  { name: "Angular", ecosystem: "npm" },
  { name: "TypeScript", ecosystem: "npm" },
  { name: "Node.js", ecosystem: "npm" },
  { name: "Express", ecosystem: "npm" },
  { name: "Fastify", ecosystem: "npm" },
  { name: "NestJS", ecosystem: "npm" },
  { name: "Prisma", ecosystem: "npm" },
  { name: "Drizzle", ecosystem: "npm" },
  { name: "Tailwind CSS", ecosystem: "npm" },
  { name: "Vite", ecosystem: "npm" },
  { name: "tRPC", ecosystem: "npm" },
  { name: "Zod", ecosystem: "npm" },
  { name: "TanStack Query", ecosystem: "npm" },
  { name: "TanStack Router", ecosystem: "npm" },
  { name: "shadcn/ui", ecosystem: "npm" },
  { name: "Radix UI", ecosystem: "npm" },
  { name: "Lucide", ecosystem: "npm" },
  { name: "Nivo", ecosystem: "npm" },
  { name: "Chart.js", ecosystem: "npm" },
  { name: "Recharts", ecosystem: "npm" },
  { name: "Three.js", ecosystem: "npm" },
  { name: "Playwright", ecosystem: "npm" },
  { name: "Cypress", ecosystem: "npm" },
  { name: "Vitest", ecosystem: "npm" },
  { name: "Jest", ecosystem: "npm" },
  { name: "Storybook", ecosystem: "npm" },
  { name: "ESLint", ecosystem: "npm" },
  { name: "Prettier", ecosystem: "npm" },
  { name: "Webpack", ecosystem: "npm" },
  { name: "Turbopack", ecosystem: "npm" },
  { name: "Turborepo", ecosystem: "npm" },
  { name: "Bun", ecosystem: "npm" },
  { name: "Deno", ecosystem: "npm" },
  { name: "Hono", ecosystem: "npm" },
  { name: "Elysia", ecosystem: "npm" },
  { name: "Astro", ecosystem: "npm" },
  { name: "Remix", ecosystem: "npm" },
  { name: "Gatsby", ecosystem: "npm" },
  { name: "Redux", ecosystem: "npm" },
  { name: "Zustand", ecosystem: "npm" },
  { name: "Jotai", ecosystem: "npm" },
  { name: "Redux Toolkit", ecosystem: "npm" },
  { name: "Supabase", ecosystem: "npm" },
  { name: "Clerk", ecosystem: "npm" },
  { name: "Auth.js", ecosystem: "npm" },
  { name: "Stripe", ecosystem: "npm" },
  { name: "OpenAI", ecosystem: "npm" },
  { name: "LangChain", ecosystem: "npm" },
  { name: "Vercel AI SDK", ecosystem: "npm" },
  { name: "RxJS", ecosystem: "npm" },
  { name: "Lodash", ecosystem: "npm" },
  { name: "date-fns", ecosystem: "npm" },
  { name: "dayjs", ecosystem: "npm" },
  { name: "Sentry", ecosystem: "npm" },
  { name: "PostCSS", ecosystem: "npm" },
  { name: "Autoprefixer", ecosystem: "npm" },
  { name: "cssnano", ecosystem: "npm" },
  { name: "SWR", ecosystem: "npm" },
  { name: "React Router", ecosystem: "npm" },
  { name: "React Native", ecosystem: "npm" },
  { name: "Expo", ecosystem: "npm" },
  { name: "Electron", ecosystem: "npm" },
  { name: "Tauri", ecosystem: "npm" },

  // Python — PyPI
  { name: "Django", ecosystem: "PyPI" },
  { name: "Flask", ecosystem: "PyPI" },
  { name: "FastAPI", ecosystem: "PyPI" },
  { name: "Pandas", ecosystem: "PyPI" },
  { name: "NumPy", ecosystem: "PyPI" },
  { name: "PyTorch", ecosystem: "PyPI" },
  { name: "TensorFlow", ecosystem: "PyPI" },
  { name: "Celery", ecosystem: "PyPI" },
  { name: "Gunicorn", ecosystem: "PyPI" },
  { name: "Uvicorn", ecosystem: "PyPI" },
  { name: "SQLAlchemy", ecosystem: "PyPI" },
  { name: "Requests", ecosystem: "PyPI" },
  { name: "Pydantic", ecosystem: "PyPI" },
  { name: "Jinja2", ecosystem: "PyPI" },
  { name: "Pytest", ecosystem: "PyPI" },
  { name: "Black", ecosystem: "PyPI" },
  { name: "Ruff", ecosystem: "PyPI" },
  { name: "Scikit-learn", ecosystem: "PyPI" },
  { name: "Matplotlib", ecosystem: "PyPI" },
  { name: "Seaborn", ecosystem: "PyPI" },
  { name: "Beautiful Soup", ecosystem: "PyPI" },
  { name: "Selenium", ecosystem: "PyPI" },
  { name: "Scrapy", ecosystem: "PyPI" },
  { name: "Psycopg2", ecosystem: "PyPI" },
  { name: "Alembic", ecosystem: "PyPI" },

  // Rust — crates.io
  { name: "Serde", ecosystem: "crates.io" },
  { name: "Tokio", ecosystem: "crates.io" },
  { name: "Axum", ecosystem: "crates.io" },
  { name: "Actix", ecosystem: "crates.io" },
  { name: "Rocket", ecosystem: "crates.io" },
  { name: "Tauri", ecosystem: "crates.io" },
  { name: "Clap", ecosystem: "crates.io" },
  { name: "Rayon", ecosystem: "crates.io" },
  { name: "Reqwest", ecosystem: "crates.io" },
  { name: "SQLx", ecosystem: "crates.io" },
  { name: "Diesel", ecosystem: "crates.io" },

  // Go
  { name: "Cobra", ecosystem: "Go" },
  { name: "Viper", ecosystem: "Go" },
  { name: "Gorilla Mux", ecosystem: "Go" },
  { name: "Chi", ecosystem: "Go" },
  { name: "Fiber", ecosystem: "Go" },
  { name: "Gin", ecosystem: "Go" },
  { name: "Echo", ecosystem: "Go" },
  { name: "Ent", ecosystem: "Go" },
  { name: "GORM", ecosystem: "Go" },
  { name: "Zap", ecosystem: "Go" },

  // Java — Maven
  { name: "Spring Boot", ecosystem: "Maven" },
  { name: "Spring", ecosystem: "Maven" },
  { name: "Hibernate", ecosystem: "Maven" },
  { name: "Log4j", ecosystem: "Maven" },
  { name: "JUnit", ecosystem: "Maven" },
  { name: "Mockito", ecosystem: "Maven" },
  { name: "Lombok", ecosystem: "Maven" },
  { name: "Gradle", ecosystem: "Maven" },
  { name: "Maven", ecosystem: "Maven" },

  // .NET — NuGet
  { name: "ASP.NET Core", ecosystem: "NuGet" },
  { name: "Entity Framework", ecosystem: "NuGet" },
  { name: "Serilog", ecosystem: "NuGet" },
  { name: "AutoMapper", ecosystem: "NuGet" },
  { name: "Newtonsoft.Json", ecosystem: "NuGet" },
  { name: "FluentValidation", ecosystem: "NuGet" },
  { name: "MediatR", ecosystem: "NuGet" },

  // Ruby — RubyGems
  { name: "Ruby on Rails", ecosystem: "RubyGems" },
  { name: "Rails", ecosystem: "RubyGems" },
  { name: "Devise", ecosystem: "RubyGems" },
  { name: "RSpec", ecosystem: "RubyGems" },
  { name: "Sidekiq", ecosystem: "RubyGems" },
  { name: "Puma", ecosystem: "RubyGems" },

  // PHP — Packagist
  { name: "Laravel", ecosystem: "Packagist" },
  { name: "Symfony", ecosystem: "Packagist" },
  { name: "Composer", ecosystem: "Packagist" },
  { name: "PHPUnit", ecosystem: "Packagist" },
  { name: "Doctrine", ecosystem: "Packagist" },

  // Infrastructure / tools (no specific ecosystem)
  { name: "PostgreSQL", ecosystem: "" },
  { name: "MySQL", ecosystem: "" },
  { name: "SQLite", ecosystem: "" },
  { name: "MongoDB", ecosystem: "" },
  { name: "Redis", ecosystem: "" },
  { name: "Docker", ecosystem: "" },
  { name: "Kubernetes", ecosystem: "" },
  { name: "Nginx", ecosystem: "" },
  { name: "Caddy", ecosystem: "" },
  { name: "Traefik", ecosystem: "" },
  { name: "AWS", ecosystem: "" },
  { name: "GCP", ecosystem: "" },
  { name: "Azure", ecosystem: "" },
  { name: "Cloudflare", ecosystem: "" },
  { name: "Vercel", ecosystem: "" },
  { name: "Netlify", ecosystem: "" },
  { name: "Railway", ecosystem: "" },
  { name: "Fly.io", ecosystem: "" },
  { name: "Render", ecosystem: "" },
  { name: "Terraform", ecosystem: "" },
  { name: "Ansible", ecosystem: "" },
  { name: "Pulumi", ecosystem: "" },
  { name: "GitHub Actions", ecosystem: "" },
  { name: "GitLab CI", ecosystem: "" },
  { name: "CircleCI", ecosystem: "" },
  { name: "Linux", ecosystem: "" },
  { name: "Ubuntu", ecosystem: "" },
  { name: "Alpine", ecosystem: "" },
  { name: "Apache Kafka", ecosystem: "" },
  { name: "RabbitMQ", ecosystem: "" },
  { name: "NATS", ecosystem: "" },
  { name: "Elasticsearch", ecosystem: "" },
  { name: "Prometheus", ecosystem: "" },
  { name: "Grafana", ecosystem: "" },
  { name: "Datadog", ecosystem: "" },
  { name: "Jaeger", ecosystem: "" },
  { name: "OpenTelemetry", ecosystem: "" },
  { name: "Git", ecosystem: "" },
  { name: "GitHub", ecosystem: "" },
];
